package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallHotgoods;
import org.linlinjava.litemall.db.domain.LitemallHotgoodsExample;

public interface LitemallHotgoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_hotgoods
     *
     * @mbg.generated
     */
    long countByExample(LitemallHotgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_hotgoods
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallHotgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_hotgoods
     *
     * @mbg.generated
     */
    int insert(LitemallHotgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_hotgoods
     *
     * @mbg.generated
     */
    int insertSelective(LitemallHotgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_hotgoods
     *
     * @mbg.generated
     */
    LitemallHotgoods selectOneByExample(LitemallHotgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_hotgoods
     *
     * @mbg.generated
     */
    LitemallHotgoods selectOneByExampleSelective(@Param("example") LitemallHotgoodsExample example, @Param("selective") LitemallHotgoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_hotgoods
     *
     * @mbg.generated
     */
    List<LitemallHotgoods> selectByExampleSelective(@Param("example") LitemallHotgoodsExample example, @Param("selective") LitemallHotgoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_hotgoods
     *
     * @mbg.generated
     */
    List<LitemallHotgoods> selectByExample(LitemallHotgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_hotgoods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallHotgoods record, @Param("example") LitemallHotgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_hotgoods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallHotgoods record, @Param("example") LitemallHotgoodsExample example);
}