server:
  port: 8085
spring:
  profiles:
    active: db, core, wx
  messages:
    encoding: UTF-8
  data:
    mongodb:
      username: wxx
      password: wxx1512
      database: recommender
      uri: mongodb://47.93.97.16:27017
  redis:
    database: 0
    port: 6379
    host: 47.93.97.16
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0

